version: '2.3'
services:
  tensorflowtts:
    build: .
    restart: always
    ports:
      - "9940-9949:9940-9949"
    volumes:
      - .:/workspace
    tty: true
    command: python tensorflow_tts_run.py > run.log
    environment:
      - CUDA_VISIBLE_DEVICES=2
